### ISSUE TITLE
Error: value method _/src/service.SwarmServiceClient.SwarmServiceList called using nil *SwarmServiceClient pointer

### ISSUE THREAD

**Issue by NikolayMurha** [docker-flow/docker-flow-swarm-listener#18]
**Description**
Hello.
I have problems with docker-flow-swarm-listener on production.
When I make API call, I have empty response and errors in log (log in "Additional information" section): 

`http://<swarm-listener-host>:8080/v1/docker-flow-swarm-listener/get-nodes`
`http://<swarm-listener-host>:8080/v1/docker-flow-swarm-listener/get-services`

Previously, the service worked fine, but after rebuilding the swarm (swarm crashed due disks issues and was rebuilt from scratch), it does not work. In the docker swarm on the developer's machine (docker for mac) everything works fine.
I have no any errors or warnings in docker service log.
Other services work good.

**Steps to reproduce the issue:**

1. Create service with spec:

```
"Spec": {
    "Name": "swarm-listener-test",
    "Labels": {},
    "TaskTemplate": {
        "ContainerSpec": {
            "Image": "dockerflow/docker-flow-swarm-listener:18.06.03-26",
            "User": "root",
            "Mounts": [
                {
                    "Type": "bind",
                    "Source": "/var/run/docker.sock",
                    "Target": "/var/run/docker.sock",
                    "ReadOnly": true
                }
            ],
            "StopGracePeriod": 10000000000,
            "DNSConfig": {},
            "Isolation": "default"
        },
        "Resources": {
            "Limits": {},
            "Reservations": {}
        },
        "RestartPolicy": {
            "Condition": "on-failure",
            "Delay": 1,
            "MaxAttempts": 100,
            "Window": 0
        },
        "Placement": {
            "Constraints": [
                "node.role == manager"
            ]
        },
        "Networks": [
            {
                "Target": "l7oh04n17mmo67dx3fmfynkdx"
            },
            {
                "Target": "p49iuwrde2dr3hvqzckr8qf50"
            },
            {
                "Target": "m6xfx93vt7ts75uw7z3s4msmv"
            },
            {
                "Target": "ocgy2fc8np11e02qu80r1dizq"
            },
            {
                "Target": "hf8bq3uwa2jr6o01tgv741u4s"
            }
        ],
        "LogDriver": {
            "Name": "json-file"
        },
        "ForceUpdate": 0,
        "Runtime": "container"
    },
    "Mode": {
        "Replicated": {
            "Replicas": 1
        }
    },
    "UpdateConfig": {
        "Parallelism": 1,
        "FailureAction": "pause",
        "Monitor": 5000000000,
        "MaxFailureRatio": 0,
        "Order": "stop-first"
    },
    "RollbackConfig": {
        "Parallelism": 1,
        "FailureAction": "pause",
        "Monitor": 5000000000,
        "MaxFailureRatio": 0,
        "Order": "stop-first"
    },
    "EndpointSpec": {
        "Mode": "vip",
        "Ports": [
            {
                "Protocol": "tcp",
                "TargetPort": 8080,
                "PublishedPort": 8080,
                "PublishMode": "ingress"
            }
        ]
    }
}
``` 

2. Call to api `curl http://<swarm-listener-host>:8080/v1/docker-flow-swarm-listener/get-services`
3. `docker service logs swarm-listener-test --since 10m -f`

**Describe the results you received:**
`curl: (52) Empty reply from server`

**Describe the results you expected:**
a successful curl invocation

**Additional information you deem important (e.g. issue happens only occasionally):**
```
swarm-listener-test.1.gwe3jjsi45n5@node0    | 2018/06/22 10:58:25 Starting Docker Flow: Swarm Listener
swarm-listener-test.1.gwe3jjsi45n5@node0    | 2018/06/22 10:58:25 Using Docker Client API version: 1.37
swarm-listener-test.1.gwe3jjsi45n5@node0    | 2018/06/22 10:58:25 Sending notifications for running services and nodes
```

`http://<swarm-listener-host>:8080/v1/docker-flow-swarm-listener/get-nodes`
```
swarm-listener-test.1.56fffyy18tn9@node0    | 2018/06/22 10:45:41 http: panic serving 10.255.0.2:61599: value method _/src/service.NodeClient.NodeList called using nil *NodeClient pointer
swarm-listener-test.1.56fffyy18tn9@node0    | goroutine 72 [running]:
swarm-listener-test.1.56fffyy18tn9@node0    | net/http.(*conn).serve.func1(0xc4200be320)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:1726 +0xd0
swarm-listener-test.1.56fffyy18tn9@node0    | panic(0x869ce0, 0xc42001e420)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/runtime/panic.go:505 +0x229
swarm-listener-test.1.56fffyy18tn9@node0    | _/src/service.(*NodeClient).NodeList(0x0, 0x957de0, 0xc42006a3c0, 0x0, 0x0, 0x0, 0x0, 0x0)
swarm-listener-test.1.56fffyy18tn9@node0    | 	<autogenerated>:1 +0x9b
swarm-listener-test.1.56fffyy18tn9@node0    | _/src/service.SwarmListener.GetNodesParameters(0x952aa0, 0x0, 0x956ce0, 0x0, 0x958d20, 0x0, 0x952ac0, 0xc4202d06c0, 0x0, 0x0, ...)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/src/service/swarmlistener.go:529 +0x66
swarm-listener-test.1.56fffyy18tn9@node0    | main.Serve.GetNodes(0x958320, 0xc4200d1300, 0xc4202d65f0, 0x9576a0, 0xc4204361c0, 0xc4200d0200)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/src/serve.go:93 +0x72
swarm-listener-test.1.56fffyy18tn9@node0    | main.(server).GetNodes-fm(0x9576a0, 0xc4204361c0, 0xc4200d0200)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/src/serve.go:54 +0x4d
swarm-listener-test.1.56fffyy18tn9@node0    | net/http.HandlerFunc.ServeHTTP(0xc4202337c0, 0x9576a0, 0xc4204361c0, 0xc4200d0200)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
swarm-listener-test.1.56fffyy18tn9@node0    | net/http.(*ServeMux).ServeHTTP(0xc4203088a0, 0x9576a0, 0xc4204361c0, 0xc4200d0200)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:2337 +0x130
swarm-listener-test.1.56fffyy18tn9@node0    | net/http.serverHandler.ServeHTTP(0xc420021380, 0x9576a0, 0xc4204361c0, 0xc4200d0200)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:2694 +0xbc
swarm-listener-test.1.56fffyy18tn9@node0    | net/http.(*conn).serve(0xc4200be320, 0x957de0, 0xc42006a340)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:1830 +0x651
swarm-listener-test.1.56fffyy18tn9@node0    | created by net/http.(*Server).Serve
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:2795 +0x27b
```
`http://<swarm-listener-host>:8080/v1/docker-flow-swarm-listener/get-services`
```
swarm-listener-test.1.56fffyy18tn9@node0    | 2018/06/22 10:52:17 http: panic serving 10.255.0.2:61976: value method _/src/service.SwarmServiceClient.SwarmServiceList called using nil *SwarmServiceClient pointer
swarm-listener-test.1.56fffyy18tn9@node0    | goroutine 171 [running]:
swarm-listener-test.1.56fffyy18tn9@node0    | net/http.(*conn).serve.func1(0xc4200be000)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:1726 +0xd0
swarm-listener-test.1.56fffyy18tn9@node0    | panic(0x869ce0, 0xc42001e240)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/runtime/panic.go:505 +0x229
swarm-listener-test.1.56fffyy18tn9@node0    | _/src/service.(*SwarmServiceClient).SwarmServiceList(0x0, 0x957de0, 0xc42006a1c0, 0x0, 0x0, 0x0, 0x0, 0x0)
swarm-listener-test.1.56fffyy18tn9@node0    | 	<autogenerated>:1 +0xca
swarm-listener-test.1.56fffyy18tn9@node0    | _/src/service.SwarmListener.GetServicesParameters(0x952aa0, 0x0, 0x956ce0, 0x0, 0x958d20, 0x0, 0x952ac0, 0xc4202d06c0, 0x0, 0x0, ...)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/src/service/swarmlistener.go:482 +0xc9
swarm-listener-test.1.56fffyy18tn9@node0    | main.Serve.GetServices(0x958320, 0xc4200d1300, 0xc4202d65f0, 0x9576a0, 0xc420202000, 0xc42022e000)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/src/serve.go:72 +0x72
swarm-listener-test.1.56fffyy18tn9@node0    | main.(server).GetServices-fm(0x9576a0, 0xc420202000, 0xc42022e000)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/src/serve.go:55 +0x4d
swarm-listener-test.1.56fffyy18tn9@node0    | net/http.HandlerFunc.ServeHTTP(0xc4202337e0, 0x9576a0, 0xc420202000, 0xc42022e000)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:1947 +0x44
swarm-listener-test.1.56fffyy18tn9@node0    | net/http.(*ServeMux).ServeHTTP(0xc4203088a0, 0x9576a0, 0xc420202000, 0xc42022e000)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:2337 +0x130
swarm-listener-test.1.56fffyy18tn9@node0    | net/http.serverHandler.ServeHTTP(0xc420021380, 0x9576a0, 0xc420202000, 0xc42022e000)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:2694 +0xbc
swarm-listener-test.1.56fffyy18tn9@node0    | net/http.(*conn).serve(0xc4200be000, 0x957de0, 0xc42006a040)
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:1830 +0x651
swarm-listener-test.1.56fffyy18tn9@node0    | created by net/http.(*Server).Serve
swarm-listener-test.1.56fffyy18tn9@node0    | 	/usr/local/go/src/net/http/server.go:2795 +0x27b
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
> docker info

Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 5
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: ************
 Is Manager: true
 ClusterID: ************
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: ***.***.***.***
 Manager Addresses:
  ***.***.***.***:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-127-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.796GiB
Name: node0
ID: ZC7H:VOON:ID4Y:BYQA:IR3F:KVMU:JBBC:73CS:CXEY:5T4S:LBZV:QR5B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thomasjpfan** [comment]
Thanks for reporting this bug. I am looking into it.

**Comment by thomasjpfan** [comment]
I updated DFSL to allow `/get-*` endpoint requests without setting any of the `DF_NOTIFY_*` env variables. Please try this out in `dockerflow/docker-flow-swarm-listener:18.06.26-27`.
